### ISSUE TITLE
Method "listMemberDelete" not found

### ISSUE THREAD

**Issue by NorchaP** [tdeNL/mgapi#1]
You forgot to include newest method

    /**
	* @example mgapi_listMemberDelete.php
	*
	* @param string $id Saraksta ID. Saraksta ID var atrast ar lists() metodi
	* @param string $email_address Epasta adrese vai "id", ko var atrast ar "listMemberInfo" metodi
	* @return boolean true ja ir izdevies, false ja nav izdevies
	*/
	function listMemberDelete($id, $email_address) {
		$params = array();
		$params["id"] = $id;
		$params["email_address"] = $email_address;
		return $this->callServer("listMemberDelete", $params);
	}

**Comment by jerome2710** [comment]
This was probably added after I've pulled the PHP API from https://dev.mailigen.com/downloads. I am accepting pull-requests if you would like to see it added soon, otherwise I will do it myself later.

**Comment by jerome2710** [comment]
Unfortunately, I noticed this function was already added in the latest version of the Mailigen PHP API. It seemed to be disappeared somehow in my code. I've re-added it and made a new minor release. Thank you for pointing this out.

**Comment by NorchaP** [comment]
It's not your fault. They added this method after my request approximately two weeks ago. And they have not change version number :D
